name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20' 

      - name: Build for Linux
        run: |
          GOOS=linux GOARCH=amd64 go build -o gpt-analysis-person

      - name: Create Release Archive
        run: |
          tar -czf gpt-analysis-person.tar.gz gpt-analysis-person

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gpt-analysis-person
          path: gpt-analysis-person.tar.gz
